### PR TITLE
Jeremybris patch 1

### PR DESCRIPTION
**Pull request by jeremybris**
To create a better score system I added 

- stars folder to **Development/Rock Band 2 (Updated)/Rock Band 2/dynamic/images/in-game**
-  and I changed the "game_osd_main.ini" in **Development/Rock Band 2 (Updated)/Rock Band 2/dynamic/**

This is just taken directly from the RB4 theme. It works perfectly fine if I remove one section from "game_osd_main.ini", the "Rank Up Flash" section. But I added that because I like that feature from the original RB2 theme.

Hopefully someone can merge the RB2, "Rank Up Flash" section in the "game_osd_main.ini" better.

### CODE REVIEW

**Comment by TheRealDannyyy** [comment]
Thanks will review this and add it soon. Currently busy with the RB3 theme.

**Comment by jeremybris** [comment]
> Thanks will review this and add it soon. Currently busy with the RB3 theme.

You are doing good work. I really like the RB 2 theme.

Plus, these changes should work for the RB 3 theme too.

**Comment by TheRealDannyyy** [comment]
Would you mind zipping up everything you've changed and upload it directly?

**Comment by TheRealDannyyy** [comment]
I've looked into the files and how it was made. It's basically done in a very sloppy way, where you only see star progression using 20 images (instead of the expected 100). I would rework this part and make it smoother.

I'm a bit concerned about the 5 star design he's using. The way that system works is by basically shifting the position of a huge 7000+ pixels texture file. The problem is that low-end systems (e.g. chipset laptop graphics) often don't support textures with that size. I will look if I can implement a workaround for this one that doesn't involve a huge texture file.

This is currently a low priority but I will try to get it into the next RB2 theme update.
You can follow progress of this feature here: #57 

(Accepted pull-request but won't merge because I want to rework and make it better.)

**Pull request closed without merging**
